// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "27eb3f4e-95ae-470a-af0a-3d77c2b20a75";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLightSwitch1Change();
void onLightSwitch2Change();
void onMotorSpeedChange();

String authUser;
String temperatureHumidity;
CloudDimmedLight lightSwitch1;
CloudDimmedLight lightSwitch2;
int motorSpeed;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(authUser, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(temperatureHumidity, READ, ON_CHANGE, NULL, 2);
  ArduinoCloud.addProperty(lightSwitch1, READWRITE, ON_CHANGE, onLightSwitch1Change);
  ArduinoCloud.addProperty(lightSwitch2, READWRITE, ON_CHANGE, onLightSwitch2Change);
  ArduinoCloud.addProperty(motorSpeed, READWRITE, ON_CHANGE, onMotorSpeedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
